### ISSUE TITLE
All the links in website still point to old .xyz domain.

### ISSUE THREAD

**Issue by saurabhshri** [coding-blocks/lab.codingblocks.com#1]
All the links in http://lab.codingblocks.com/ still point to old domain http://lab.codingblocks.xyz/ which leads to a 404.

**Comment by saurabhshri** [comment]
If these changes look okay to you, I'll send a PR. (https://github.com/coding-blocks/lab.codingblocks.xyz/compare/gh-pages...saurabhshri:com)

**Comment by championswimmer** [comment]
Please make the changes!  Would be much appreciated

**Comment by saurabhshri** [comment]
@championswimmer Done! :)
