### ISSUE TITLE
The page has two BOSS Icon in the Top Navbar

### ISSUE THREAD

**Issue by codedsun** [coding-blocks/lab.codingblocks.com#25]
Currently the page has two icons at the top navbar of BOSS at http://lab.codingblocks.com
What shall be done? 
Is that something to be resolved to BOSS-2018, BOSS -2017 or something else.
@championswimmer @prateek27

**Comment by championswimmer** [comment]
Yeah we need to remove the BOSS 2017 top level link (or make it a dropdown)

**Comment by codedsun** [comment]
Okay will send a PR by tonight! :)

**Comment by adityac8** [comment]
Is this issue lies under BOSS?

**Comment by championswimmer** [comment]
fixed
