### ISSUE TITLE
Markdown rendering and typos in BOSS 2019 page

### ISSUE THREAD

**Issue by harshraj22** [coding-blocks/lab.codingblocks.com#52]
There are various Grammatical errors and markdown rendering issues in the [BOSS 2019](https://github.com/coding-blocks/lab.codingblocks.com/blob/gh-pages/_pages/boss_2019.md) page.

**Comment by harshraj22** [comment]
Working on it.

**Comment by DhruvTrehan** [comment]
This issue is open . How to make changes to it .
